# Generated by Django 5.2.1 on 2025-05-23 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=3)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')])),
                ('cpf', models.CharField(max_length=11)),
                ('convenio', models.CharField(choices=[('SUS', 'SUS'), ('Unimed', 'Unimed'), ('Hapvida', 'Hapvida'), ('Amil', 'Amil'), ('Bradesco Saude', 'Bradesco Saude')])),
                ('hora_chegada', models.TimeField(blank=True, null=True)),
                ('temperatura', models.CharField(max_length=2)),
                ('pulso', models.CharField(max_length=2)),
                ('queixa', models.CharField(max_length=1000)),
                ('dor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('inicio_sintomas', models.DateField(blank=True, null=True)),
                ('sintomas_associados', models.CharField(choices=[('Febre', 'Febre'), ('Dor de Cabeça', 'Dor de Cabeça'), ('Falta de Ar', 'Falta de Ar'), ('Náusea/Vômito', 'Náusea/Vômito'), ('Tontura', 'Tontura'), ('Fraqueza', 'Fraqueza')])),
                ('observacoes', models.CharField(blank=True, max_length=1000, null=True)),
                ('classificacao', models.CharField(choices=[('Vermelho', 'Emergência'), ('Laranja', 'Muito Urgente'), ('Amarelo', 'Urgente'), ('Verde', 'Pouco Urgente'), ('Azul', 'Não Urgente')])),
                ('status_atendimento', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento'), ('Concluido', 'Concluido')], default='Esperando', max_length=20)),
            ],
        ),
    ]
