# Generated by Django 5.2.1 on 2025-08-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('Vermelho', 'Emergência'), ('Laranja', 'Muito Urgente'), ('Amarelo', 'Urgente'), ('Verde', 'Pouco Urgente'), ('Azul', 'Não Urgente')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='encaminhamento',
            field=models.CharField(blank=True, choices=[('Clinica Medica', 'Clinica Medica'), ('Ortopedia', 'Ortopedia'), ('Pediatria', 'Pediatria'), ('Cardiologia', 'Cardiologia'), ('Neurologia', 'Neurologia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='frequenciaRespiratoria',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='justificativa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pulso',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='status_atendimento',
            field=models.CharField(blank=True, choices=[('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento'), ('Concluido', 'Concluido')], default='Esperando', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='temperatura',
            field=models.CharField(max_length=3),
        ),
    ]
