# Generated by Django 5.2.1 on 2025-05-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='classificacao',
            field=models.CharField(choices=[('Vermelho', 'Emergência'), ('Laranja', 'Muito Urgente'), ('Amarelo', 'Urgente'), ('Verde', 'Pouco Urgente'), ('Azul', 'Não Urgente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='convenio',
            field=models.CharField(choices=[('SUS', 'SUS'), ('Unimed', 'Unimed'), ('Hapvida', 'Hapvida'), ('Amil', 'Amil'), ('Bradesco Saude', 'Bradesco Saude')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sintomas_associados',
            field=models.CharField(choices=[('Febre', 'Febre'), ('Dor de Cabeça', 'Dor de Cabeça'), ('Falta de Ar', 'Falta de Ar'), ('Náusea/Vômito', 'Náusea/Vômito'), ('Tontura', 'Tontura'), ('Fraqueza', 'Fraqueza')], max_length=50),
        ),
    ]
