# Generated by Django 5.2.1 on 2025-05-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_alter_paciente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_chegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
