# Generated by Django 5.2.1 on 2025-09-02 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_alter_feedbacktriagem_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProntuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Descrição do Atendimento / Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_prontuario', to='triagem.paciente')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
