# Generated by Django 5.2.1 on 2025-08-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_alter_paciente_classificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='status_atendimento',
            field=models.CharField(blank=True, choices=[('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento'), ('Concluido', 'Concluido')], default='Aguardando', max_length=20, null=True),
        ),
    ]
