# Generated by Django 5.2.1 on 2025-08-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='especializacao',
            field=models.CharField(blank=True, choices=[('CLINICA_GERAL', 'Clínica Geral'), ('CARDIOLOGIA', 'Cardiologia'), ('ORTOPEDIA', 'Ortopedia'), ('PEDIATRIA', 'Pediatria'), ('NEUROLOGIA', 'Neurologia'), ('OUTRA', 'Outra')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registro_profissional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
