# Generated by Django 5.2.1 on 2025-08-31 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0003_customuser_especializacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medico_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_atendidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
