# Generated by Django 5.2.1 on 2025-08-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0003_alter_paciente_status_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sintomas_associados',
            field=models.CharField(choices=[('Dor_Toracica', 'Dor Torácica / Aperto no Peito'), ('Falta_de_Ar', 'Falta de Ar / Dificuldade para Respirar'), ('Alteracao_Neurologica_Grave', 'Alteração de Consciência / Convulsão / Confusão'), ('Sangramento_Ativo', 'Sangramento Ativo / Vômito ou Fezes com Sangue'), ('Febre', 'Febre / Calafrios'), ('Dor_de_Cabeca', 'Dor de Cabeça'), ('Tontura_MalEstar', 'Tontura / Fraqueza / Mal-estar Geral'), ('Sintomas_Respiratorios_Leves', 'Tosse / Espirros / Dor de Garganta'), ('Dor_Abdominal', 'Dor Abdominal / Cólica'), ('Sintomas_Gastrointestinais', 'Náusea / Vômito / Diarreia'), ('Lesao_Trauma', 'Lesão / Trauma / Queda Recente'), ('Dor_Locomotora', 'Dor Muscular / Articular / Lombar'), ('Reacao_Alergica_Pele', 'Reação Alérgica / Erupção na Pele / Inchaço'), ('Queixa_Urinaria', 'Queixa Urinária (Dor ao urinar / Sangue na urina)'), ('Outro', 'Outro')], max_length=50),
        ),
    ]
