# Generated by Django 5.2.1 on 2025-09-09 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0003_entradaprontuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='frequenciaRespiratoria',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)], verbose_name='Frequência Respiratória'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='glicemia',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pressao_diastolica',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pressao_sistolica',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pulso',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='saturacao',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='temperatura',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(34.0), django.core.validators.MaxValueValidator(43.0)]),
        ),
    ]
