# Generated by Django 5.2.1 on 2025-08-31 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0004_paciente_medico_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='hora_fim_atendimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hora_inicio_atendimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hora_chegada',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
