# Generated by Django 5.2.1 on 2025-09-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0004_alter_paciente_frequenciarespiratoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='frequenciaRespiratoria',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='glicemia',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pressao_diastolica',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pressao_sistolica',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pulso',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='saturacao',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='temperatura',
            field=models.FloatField(max_length=3),
        ),
    ]
