# Generated by Django 5.2.1 on 2025-08-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0004_alter_paciente_sintomas_associados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='temperatura',
            field=models.FloatField(max_length=3),
        ),
    ]
