# Generated by Django 5.2.1 on 2025-08-31 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0005_paciente_hora_fim_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='hora_chegada',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
