# Generated by Django 5.2.1 on 2025-09-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0005_alter_paciente_frequenciarespiratoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
