# Generated by Django 5.2.1 on 2025-08-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0005_alter_paciente_temperatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='status_atendimento',
        ),
        migrations.AddField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Em Atendimento', 'Em Atendimento'), ('Concluido', 'Concluído')], default='Aguardando', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pressaoArterial',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='temperatura',
            field=models.FloatField(),
        ),
    ]
