# Generated by Django 5.2.1 on 2025-08-31 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0006_alter_paciente_hora_chegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='hora_chegada',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
