# Generated by Django 5.2.1 on 2025-08-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0006_remove_paciente_status_atendimento_paciente_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='status',
        ),
        migrations.AddField(
            model_name='paciente',
            name='status_atendimento',
            field=models.CharField(blank=True, choices=[('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento'), ('Concluido', 'Concluido')], default='Aguardando', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pressaoArterial',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='temperatura',
            field=models.FloatField(max_length=3),
        ),
    ]
