# Generated by Django 5.2.1 on 2025-09-09 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0006_alter_customuser_cpf_alter_paciente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='temperatura',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(34.0), django.core.validators.MaxValueValidator(40.0)]),
        ),
    ]
