# Generated by Django 5.2.1 on 2025-08-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0007_alter_paciente_hora_chegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='inicio_sintomas',
            field=models.DateField(auto_now=True),
        ),
    ]
