# Generated by Django 5.2.1 on 2025-09-09 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0007_alter_paciente_temperatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='frequenciaRespiratoria',
            field=models.CharField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='glicemia',
            field=models.CharField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pressao_diastolica',
            field=models.CharField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pressao_sistolica',
            field=models.CharField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pulso',
            field=models.CharField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='saturacao',
            field=models.CharField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='temperatura',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(33.0), django.core.validators.MaxValueValidator(43.0)]),
        ),
    ]
