# Generated by Django 5.2.1 on 2025-08-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0008_alter_paciente_inicio_sintomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='inicio_sintomas',
            field=models.DateField(),
        ),
    ]
