# Generated by Django 5.2.1 on 2025-08-31 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0009_alter_paciente_inicio_sintomas'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triagem_correta', models.BooleanField(default=True, verbose_name='A classificação do sistema foi correta?')),
                ('classificacao_correta', models.CharField(blank=True, choices=[('Vermelho', 'Emergência'), ('Laranja', 'Muito Urgente'), ('Amarelo', 'Urgente'), ('Verde', 'Pouco Urgente'), ('Azul', 'Não Urgente')], max_length=50, null=True, verbose_name='Se não, qual seria a classificação correta?')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo da reclassificação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='triagem.paciente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
