# Generated by Django 5.2.1 on 2025-09-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0009_alter_paciente_frequenciarespiratoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktriagem',
            name='triagem_correta',
            field=models.BooleanField(verbose_name='A classificação do sistema foi correta?'),
        ),
    ]
