# Generated by Django 5.2.1 on 2025-10-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0010_alter_feedbacktriagem_triagem_correta'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktriagem',
            name='status',
            field=models.CharField(choices=[('EM_ANALISE', 'Em Análise'), ('ACATADO', 'Acatado'), ('NAO_ACATADO', 'Não Acatado')], default='EM_ANALISE', max_length=20, verbose_name='Status do Feedback'),
        ),
    ]
