# Generated by Django 5.2.1 on 2025-10-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0011_feedbacktriagem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF do Responsável'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Responsável'),
        ),
    ]
