# Generated by Django 5.2.1 on 2025-10-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0012_paciente_cpf_responsavel_paciente_nome_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('ATENDENTE', 'Atendente'), ('MEDICO', 'Médico'), ('TECNICO_ENFERMAGEM', 'Téc. de Enfermagem'), ('ADMIN', 'Admin')], default='ATENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento'), ('Concluido', 'Concluido')], default='Pendente', max_length=30),
        ),
    ]
