# Generated by Django 5.2.1 on 2025-10-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0013_alter_customuser_tipo_usuario_alter_paciente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='status',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento'), ('Concluido', 'Concluido')], default='Pendente', max_length=30, null=True),
        ),
    ]
