# Generated by Django 5.2.1 on 2025-10-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0014_alter_paciente_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='fotos_perfil/default.jpg', null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
