# Generated by Django 5.2.1 on 2025-10-17 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0015_customuser_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição do Arquivo')),
                ('arquivo', models.FileField(upload_to='anexos_pacientes/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='triagem.paciente')),
            ],
        ),
    ]
