# Generated by Django 5.2.1 on 2025-10-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0016_anexopaciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registro_profissional',
        ),
        migrations.AddField(
            model_name='customuser',
            name='coren',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='COREN (Apenas para Téc. de Enfermagem)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='crm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CRM (Apenas para Médicos)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uf_registro',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True, verbose_name='UF do Registro Profissional'),
        ),
    ]
