# Generated by Django 5.2.1 on 2025-10-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0018_logacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
