# Generated by Django 5.2.1 on 2025-10-21 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0019_unidadesaude'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexopaciente',
            name='unidade_saude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triagem.unidadesaude'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unidade_saude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triagem.unidadesaude'),
        ),
        migrations.AddField(
            model_name='entradaprontuario',
            name='unidade_saude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triagem.unidadesaude'),
        ),
        migrations.AddField(
            model_name='feedbacktriagem',
            name='unidade_saude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triagem.unidadesaude'),
        ),
        migrations.AddField(
            model_name='logacao',
            name='unidade_saude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triagem.unidadesaude'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='unidade_saude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triagem.unidadesaude'),
        ),
    ]
