# Generated by Django 5.2.1 on 2025-11-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0020_anexopaciente_unidade_saude_customuser_unidade_saude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='justificativa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
