# Generated by Django 5.2.1 on 2025-12-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0021_alter_paciente_cpf_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('ATENDENTE', 'Atendente'), ('MEDICO', 'Médico'), ('ENFERMEIRO', 'Enfermeiro'), ('ADMIN', 'Admin')], default='ATENDENTE', max_length=20),
        ),
    ]
