# Generated by Django 5.2.1 on 2026-02-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0024_paciente_bairro_paciente_cep_paciente_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
