# Generated by Django 5.2.1 on 2026-02-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0025_paciente_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
