# Generated by Django 5.2.1 on 2026-03-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0026_paciente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='coren',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='COREN'),
        ),
    ]
