# Generated by Django 5.2.1 on 2026-03-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0029_alter_customuser_coren'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='crm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CRM'),
        ),
    ]
